language: ruby
rvm:
  - 2.0.0-p647
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0

before_install:
  - wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
  - gem install bundler

install:
  - bundle install --path vendor/bundle
