language: ruby
rvm:
  - 2.3.3
  - 2.4.0
  - 2.5.1

before_install:
  - wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
  - gem install bundler

install:
  - gem update --system
  - gem install bundler
  - bundle install --path vendor/bundle
